services:
  hls-public-proxy:
    build: .
    container_name: hls-public-proxy
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      MAX_PARALLEL: 64
      # DEFAULT_REFERER: https://example.com/
      # PROXY_BASE: https://localhost:3000/proxy/
      # ENABLE_FLARESOLVERR: 0
      # FLARESOLVERR: http://flaresolverr:8191
      SEGMENT_CACHE_MAX: 500
      SEGMENT_CACHE_TTL_MS: 90000
      MANIFEST_CACHE_MAX: 200
      MANIFEST_CACHE_TTL_MS: 4000
      SEGMENT_CACHE_MAX_BYTES: 2000000
